--drop table dispositivo
--drop table dispositivo
--drop table nivel
--drop table tipo_dispositivo
--drop table dispositivos_encendidos
--drop table propiedad

create table parametros (
	prmt_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, prmt_nombre varchar(60) UNIQUE not null
	, prmt_valor varchar(100) not null
);


create table genero (
	gnro_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, gnro_nombre varchar(60) UNIQUE not null
);

create table tipo_usuario (
	tpus_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, tpus_nombre varchar(60) UNIQUE not null
);

create table tipo_accion_movimiento (
	tpam_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, tpam_nombre varchar(60) UNIQUE not null
);

create table tipo_movimiento (
	tpmv_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, tpmv_nombre varchar(60) UNIQUE not null
);

create table tipo_dispositivo_general (
	tpdg_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, tpdg_nombre varchar(60) UNIQUE not null
	, tpdg_control_tiempo boolean not null
	, tpdg_activo boolean not null
);

create table tipo_dispositivo (
	tpdp_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, tpdg_id integer not null
	, tpdp_nombre varchar(60) UNIQUE not null
	, tpdp_activo boolean not null

	, foreign key (tpdg_id) references tipo_dispositivo_general (tpdg_id)
);

create table cliente (
	clnt_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, clnt_nombre varchar(60) UNIQUE not null
	, clnt_mail varchar(500) not null
	, clnt_fecha_nacimiento datetime
	, gnro_id integer not null
	, clnt_celular integer
	, clnt_usuario_creador varchar(60)
	, clnt_fecha_creacion datetime
	, clnt_usuario_actualizador varchar(60)
	, clnt_fecha_actualizacion datetime

	, foreign key (gnro_id) references genero (gnro_id)
);

create table propiedad (
	prpd_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, prpd_nombre varchar(60) UNIQUE not null
--	, user_id integer not null
	, prpd_mail varchar(500) not null
	, prpd_direccion varchar(500)
	, prpd_usuario_creador varchar(60)
	, prpd_fecha_creacion datetime
	, prpd_usuario_actualizador varchar(60)
	, prpd_fecha_actualizacion datetime

--	, foreign key (user_id) references usuario (user_id)
);
	
create table nivel (
	nvel_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, prpd_id integer not null
	, nvel_nombre varchar(60) UNIQUE not null
	, nvel_activo boolean not null
	, nvel_usuario_creador varchar(60)
	, nvel_fecha_creacion datetime
	, nvel_usuario_actualizador varchar(60)
	, nvel_fecha_actualizacion datetime

	, foreign key (prpd_id) references propiedad (prpd_id)
);

create table zona (
	zona_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, nvel_id integer not null
	, zona_nombre varchar(60) not null
	, zona_activo boolean not null
	, zona_usuario_creador varchar(60)
	, zona_fecha_creacion datetime
	, zona_usuario_actualizador varchar(60)
	, zona_fecha_actualizacion datetime

	, foreign key (nvel_id) references nivel (nvel_id)
);
  

create table dispositivo (
	dpst_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, zona_id integer not null
	, tpdp_id integer not null
	, dpst_codigo varchar(10) UNIQUE not null
	, dpst_nombre varchar(60)
	, dpst_descripcion varchar(1000)
	, dpst_nivel_ruido integer
	, dpst_nivel_senhal integer
	, dpst_activo boolean not null
	, dpst_estado boolean not null
	, dpst_alarmado boolean not null
	, dpst_retardo integer
	, dpst_dimmer integer
	, dpst_ultimo_encendido datetime
	, dpst_usuario_creador varchar(60)
	, dpst_fecha_creacion datetime
	, dpst_usuario_actualizador varchar(60)
	, dpst_fecha_actualizacion datetime

	, foreign key (zona_id) references zona (zona_id)
	, foreign key (tpdp_id) references tipo_dispositivo (tpdp_id)
);

create table tipo_camara (
	tpcm_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, tpcm_modelo varchar(60) UNIQUE not null
);

create table camara (
	cmra_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, dpst_id integer not null
	, tpcm_id integer not null

	, cmra_nombre varchar(60) not null
	, cmra_ip varchar(40) not null
	, cmra_port integer not null

	, foreign key (dpst_id) references dispositivo (dpst_id)
	, foreign key (tpcm_id) references tipo_camara (tpcm_id)
);


create table mapa (
	mapa_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, nvel_id integer not null
	, mapa_nombre varchar(60) not null
	, mapa_informacion varchar(1000) null
	, mapa_descripcion varchar(5000) null
	, mapa_path varchar(1000) not null
	, mapa_orden integer not null
	, mapa_activo boolean not null
	, mapa_usuario_creador varchar(60)
	, mapa_fecha_creacion datetime
	, mapa_usuario_actualizador varchar(60)
	, mapa_fecha_actualizacion datetime

	, foreign key (nvel_id) references nivel (nvel_id)
);

create table coordenada (
	crdn_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, mapa_id integer not null
	, dpst_id integer not null
	, crdn_proporcion_x float not null
	, crdn_proporcion_y float not null
	, crdn_usuario_creador varchar(60)
	, crdn_fecha_creacion datetime
	, crdn_usuario_actualizador varchar(60)
	, crdn_fecha_actualizacion datetime
	
	, foreign key (mapa_id) references mapa (mapa_id)
	, foreign key (dpst_id) references dispositivo (dpst_id)
);

create table tipo_programacion (
	tppg_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, tppg_nombre varchar(100) not null
);

create table dias (
	dias_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, dias_valor integer not null
	, dias_nombre varchar(100) not null
);

create table programacion (
	prgm_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, tppg_id integer not null
	, dpst_id integer not null
	, prgm_motivo varchar(1000)
	, prgm_activo boolean not null
	, prgm_usuario_creador varchar(60)
	, prgm_fecha_creacion datetime
	, prgm_usuario_actualizador varchar(60)
	, prgm_fecha_actualizacion datetime
	
	, foreign key (tppg_id) references tipo_programacion (tppg_id)
	, foreign key (dpst_id) references dispositivo (dpst_id)
);

create table detalle_programacion (
	pgdr_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, prgm_id integer not null
	, dias_id integer not null
	, prgm_encendido time not null
	, prgm_apagado time not null
	, prgm_usuario_creador varchar(60)
	, prgm_fecha_creacion datetime
	, prgm_usuario_actualizador varchar(60)
	, prgm_fecha_actualizacion datetime
	
	, foreign key (prgm_id) references programacion (prgm_id)
	, foreign key (dias_id) references dias (dias_id)
);

	
create table dispositivos_encendidos (
	dpec_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, dpst_id integer not null
	, dpec_fecha datetime not null

	, foreign key (dpst_id) references dispositivo (dpst_id)
);

create table dispositivos_alarmados (
	dpal_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, dpst_id integer not null
	, dpal_fecha datetime not null
	, dpal_mail varchar(500) 

	, foreign key (dpst_id) references dispositivo (dpst_id)
);



create table estado_sincronizacion (
	etsz_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, etsz_nombre varchar(60) UNIQUE not null
);


create table sincronizacion (
	snzc_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, snzc_inicio datetime
	, snzc_fin datetime
	, snzc_usuario_creador varchar(60)
	, snzc_fecha_creacion datetime
	, snzc_usuario_actualizador varchar(60)
	, snzc_fecha_actualizacion datetime
);

create table detalle_sincronizacion (
	dtsz_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, snzc_id integer not null
	, dpst_id integer not null
	, etsz_id integer not null
	, dtsz_usuario_creador varchar(60)
	, dtsz_fecha_creacion datetime
	, dtsz_usuario_actualizador varchar(60)
	, dtsz_fecha_actualizacion datetime
	
	, foreign key (dpst_id) references dispositivo (dpst_id)
	, foreign key (snzc_id) references sincronizacion (snzc_id)
	, foreign key (etsz_id) references estado_sincronizacion (etsz_id)
);

create table apagado_programado (
	appr_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, dpst_id integer not null
	, appr_apagado time not null
	, appr_usuario_creador varchar(60)
	, appr_fecha_creacion datetime
	, appr_usuario_actualizador varchar(60)
	, appr_fecha_actualizacion datetime
	
	, foreign key (dpst_id) references dispositivo (dpst_id)
);

create table tipo_clima (
	tpcm_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, tpcm_nombre varchar(60) not null
);

create table clima (
	clma_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, tpcm_id integer not null
	, clma_temperatura integer not null
	, clma_fecha datetime
	, clma_fecha_publicacion datetime
	, clma_velocidad_viento float
	, clma_direccion_viento integer
	, clma_sensacion_termica integer
	, clma_humedad integer
	, clma_presion float
	, clma_visibilidad float

	, foreign key (tpcm_id) references tipo_clima (tpcm_id)
);

create table proyeccion_clima (
	pjcm_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, clma_id integer not null
	, tpcm_id integer not null
	, pjcm_temperatura_minima integer not null
	, pjcm_temperatura_maxima integer not null
	, pjcm_fecha datetime
	
	, foreign key (clma_id) references clima (clma_id)
	, foreign key (tpcm_id) references tipo_clima (tpcm_id)
);

create table tipo_evento (
	tpev_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, tpev_nombre varchar(60) UNIQUE not null
);


create table evento (
	evnt_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, tpev_id integer not null
	, tpdp_id integer null
	, evnt_fecha datetime not null
	, dpst_codigo varchar(3) null
	, dpst_nombre varchar(60)
	, evnt_descripcion varchar(5000)
	, evnt_dato1 varchar(1000)
	, evnt_dato2 varchar(1000)

	, foreign key (tpev_id) references tipo_evento (tpev_id)
	, foreign key (tpdp_id) references tipo_dispositivo (tpdp_id)
);

create table consumo (
	cnsm_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, cnsm_fecha_inicio datetime not null
	, cnsm_fecha_fin datetime null
	, tpdp_id integer not null
	, dpst_codigo varchar(3) not null
	, dpst_nombre varchar(60)

	, foreign key (tpdp_id) references tipo_dispositivo (tpdp_id)
);

create table accion_movimiento (
	acmv_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, tpmv_id integer not null
	, dpst_id integer not null
	, acmv_motivo varchar(1000)
	, acmv_activo boolean not null
  , acmv_desde time not null
  , acmv_hasta time not null
	, acmv_usuario_creador varchar(60)
	, acmv_fecha_creacion datetime
	, acmv_usuario_actualizador varchar(60)
	, acmv_fecha_actualizacion datetime

	, foreign key (tpmv_id) references tipo_movimiento (tpmv_id)
	, foreign key (dpst_id) references dispositivo (dpst_id)
);

create table detalle_accion_movimiento (
	damv_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
	, acmv_id integer not null
	, tpam_id integer not null
	, dpst_id integer null
	, damv_usuario_creador varchar(60)
	, damv_fecha_creacion datetime
	, damv_usuario_actualizador varchar(60)
	, damv_fecha_actualizacion datetime

	, foreign key (acmv_id) references accion_movimiento (acmv_id)
	, foreign key (tpam_id) references tipo_accion_movimiento (tpam_id)
	, foreign key (dpst_id) references dispositivo (dpst_id)
);
